name: 构建和压缩EXE文件

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:

    - name: 检出代码
      uses: actions/checkout@v3

    - name: 设置Python环境
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: 安装依赖并输出nuitka路径
      run: |
        python -m pip install --upgrade pip
        pip install pillow
        python -m pip install nuitka  

    - name: 检查nuitka的安装情况
      run: python -m nuitka --version
        
    - name: 安装upx
      run: choco install upx

    - name: 编译EXE文件
      run: |
        python -m nuitka --follow-imports AVJPWConverter.py
        dir

    - name: 压缩EXE文件
      shell: pwsh
      run: upx --best .\AVJPWConverter.exe

    - name: 上传EXE文件
      uses: actions/upload-artifact@v2
      with:
        name: AVJPWConverter-EXE
        path: ./AVJPWConverter.exe
