name: Build and Compress EXE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pillow pillow-avif
        
    - name: Compile EXE
      run: nuitka --follow-imports --windows-disable-console AVJPWConverter.py
      
    - name: Compress EXE
      run: upx --best AVJPWConverter.dist/AVJPWConverter.exe
      
    - name: Upload EXE artifact
      uses: actions/upload-artifact@v2
      with:
        name: AVJPWConverter-EXE
        path: AVJPWConverter.dist/AVJPWConverter.exe
