name: 构建和压缩EXE文件

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:

    - name: 检出代码
      uses: actions/checkout@v3

    - name: 设置Python环境
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install pillow
        pip install pillow-avif-plugin
        python -m pip install nuitka  
        
    - name: 安装upx
      run: choco install upx

    - name: Set PYTHONIOENCODING environment variable
      run: echo "PYTHONIOENCODING=utf-8" >> $GITHUB_ENV
      
    - name: 编译EXE文件
      run: nuitka --follow-imports --include-module=encodings AVJPWConverter.py

    - name: 压缩EXE文件
      shell: pwsh
      run: upx --best .\AVJPWConverter.exe

    - name: 上传EXE文件
      uses: actions/upload-artifact@v3
      with:
        name: AVJPWConverter-EXE
        path: ./AVJPWConverter.exe
