name: PyQt5版PyOxidizer编译

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 安装Python环境
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: 安装Rust环境
        uses: dtolnay/rust-toolchain@stable

      - name: 安装PyOxidizer
        run: pip install pyoxidizer

      - name: 安装依赖
        run: pip install -r requirements.txt

      - name: 生成pyoxidizer.bzl
        run: pyoxidizer init-config --application-name AVJPWConverterPyQt5 --python-exe AVJPWConverterPyQt5.py

      - name: 编译EXE文件
        run: pyoxidizer build

      - name: 上传EXE文件
        uses: actions/upload-artifact@v4
        with:
          name: AVJPWConverterPyQt5-PyOxidizer
          path: build/x86_64-pc-windows-msvc/release/install/
