name: PyQt5版PyOxidizer编译

on:
  workflow_dispatch:
  push:
    branches:
      - test

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 安装Python环境
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # 改为3.10版本

      - name: 安装Rust环境
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Rust缓存
        uses: Swatinem/rust-cache@v2

      - name: 安装PyOxidizer
        run: pip install pyoxidizer

      - name: 安装依赖
        run: pip install -r requirements.txt

      - name: 编译EXE文件
        run: |
          # 构建发布版本
          pyoxidizer build --release
          
          # 准备发布目录
          $targetDir = "build/x86_64-pc-windows-msvc/release/install"
          $distDir = "build/x86_64-pc-windows-msvc/release/dist"
          New-Item -ItemType Directory -Force -Path $targetDir
          
          # 复制Python DLL
          $pythonPath = (Get-Command python).Path
          $pythonDir = Split-Path $pythonPath -Parent
          Copy-Item "$pythonDir/python310.dll" -Destination $targetDir -Force
          
          # 复制所有构建文件
          if (Test-Path $distDir) {
              Copy-Item "$distDir/*" -Destination $targetDir -Recurse -Force
              
              # 显示文件大小信息
              Write-Host "文件大小信息:"
              Get-ChildItem $targetDir -Recurse | 
                Where-Object { !$_.PSIsContainer } |
                Select-Object FullName, @{Name="Size(MB)";Expression={$_.Length / 1MB}}
          } else {
              Write-Error "构建目录未找到: $distDir"
              Get-ChildItem "build/x86_64-pc-windows-msvc/release" -Recurse
              exit 1
          }

      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: AVJPWConverterPyQt5-PyOxidizer
          path: build/x86_64-pc-windows-msvc/release/install/**/*
          if-no-files-found: error