name: PyQt5版exe构建

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-2019

    steps:

    - name: 检出代码
      uses: actions/checkout@v4

    - name: 设置Python环境
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install pillow
        pip install pillow-avif-plugin
        pip install PyQt5
        pip install PyQt5-sip
        python -m pip install nuitka

    - name: 下载并解压Dependency Walker
      run: |
        curl -L -o depends.zip http://dependencywalker.com/depends22_x64.zip
        Expand-Archive -Path depends.zip -DestinationPath ./depends

    - name: 安装 MinGW64
      run: |
        choco install mingw

    - name: 设置 MinGW64 编译器路径
      run: |
        $env:Path += ";C:\Program Files\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin"

    - name: 编译EXE文件
      run: |
        echo "Y" | nuitka --standalone --onefile --enable-plugin=pyqt5 --windows-console-mode=disable AVJPWConverterPyQt5.py --output-dir=./dist

    - name: 列出dist目录的文件
      shell: pwsh
      run: |
        Write-Output "Checking contents of ./dist"
        Get-ChildItem -Path ./dist

    - name: 列出当前目录的文件列表
      shell: pwsh
      run: Get-ChildItem -Force

    - name: 上传EXE文件
      uses: actions/upload-artifact@v4
      with:
        name: AVJPWConverterPyQt5-exe
        path: ./dist/AVJPWConverterPyQt5.exe
