name: PyQt5版exe构建

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-2022

    steps:

    - name: 检出代码
      uses: actions/checkout@v4

    - name: 设置Python环境
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install pillow
        pip install pillow-avif-plugin==1.4.3 #新版安装依赖错误 指定1.4.3 好像是1.5.0后没预编译wheel文件
        pip install PyQt5
        pip install send2trash
        pip install psutil
        pip install configparser
        pip install futures
        python -m pip install nuitka

    - name: 编译EXE文件
      run: |
        echo Yes | nuitka --standalone --follow-imports --onefile --enable-plugin=pyqt5 --windows-console-mode=disable AVJPWConverterPyQt5.py

    - name: 列出当前目录的文件列表
      shell: pwsh
      run: Get-ChildItem -Force

    - name: 上传EXE文件
      uses: actions/upload-artifact@v4
      with:
        name: AVJPWConverterPyQt5-exe
        path: ./AVJPWConverterPyQt5.exe